from datetime import datetime
from pathlib import Path
import random

# Today's date
today = datetime.now().strftime("%Y-%m-%d")

# Random number of tasks between 25 and 50
total_tasks = random.randint(25, 50)

categories = [
    "Cpp",
    "Python",
    "Data-Structures",
    "SQL"
]

tasks = {
    "Cpp": [
        "Write a program to find the largest of three numbers.",
        "Write a program to calculate factorial of a number.",
        "Write a program to check whether a number is prime.",
        "Write a program to reverse a number.",
        "Write a program to check whether a number is palindrome.",
        "Write a program to calculate the sum of array elements.",
        "Write a program to find the smallest element in an array.",
        "Write a program to count even and odd numbers.",
        "Write a program to swap two numbers.",
        "Write a program to calculate simple interest."
    ],

    "Python": [
        "Write a program to find the largest number in a list.",
        "Write a program to reverse a string.",
        "Write a program to count vowels in a string.",
        "Write a program to calculate factorial.",
        "Write a program to check whether a number is prime.",
        "Write a program to find the sum of list elements.",
        "Write a program to remove duplicates from a list.",
        "Write a program to count words in a sentence.",
        "Write a program to find the smallest number in a list.",
        "Write a program to calculate the average of numbers."
    ],

    "Data-Structures": [
        "Implement linear search.",
        "Implement binary search.",
        "Create and display an array.",
        "Implement stack using an array.",
        "Implement queue using an array.",
        "Insert an element into an array.",
        "Delete an element from an array.",
        "Traverse a linked list.",
        "Create a singly linked list.",
        "Count nodes in a linked list."
    ],

    "SQL": [
        "Create a Student table.",
        "Insert five student records.",
        "Display all students.",
        "Find students with marks greater than 80.",
        "Update a student's marks.",
        "Delete a student record.",
        "Sort students by marks.",
        "Count total students.",
        "Find the maximum marks.",
        "Find the average marks."
    ]
}

# Create today's folder
base_folder = Path("Daily-Progress") / today
base_folder.mkdir(parents=True, exist_ok=True)

# Generate random tasks
for number in range(1, total_tasks + 1):

    category = random.choice(categories)
    task = random.choice(tasks[category])

    category_folder = base_folder / category
    category_folder.mkdir(parents=True, exist_ok=True)

    filename = category_folder / f"task_{number:02d}.md"

    content = f"""# Daily Practice Task {number}

**Date:** {today}

**Category:** {category}

## Task

{task}

## Practice Status

- [ ] Started
- [ ] Solved
- [ ] Understood
"""

    filename.write_text(content, encoding="utf-8")


# Create daily summary
summary = base_folder / "README.md"

summary.write_text(
    f"""# Daily Practice - {today}

Total tasks generated today: **{total_tasks}**

Categories:
- C++
- Python
- Data Structures
- SQL

These tasks were automatically generated by GitHub Actions.
""",
    encoding="utf-8"
)

print(f"Successfully generated {total_tasks} tasks for {today}.")
